### ISSUE TITLE
How to Install angular-wordpress-seed

### ISSUE THREAD

**Issue by BruceYangMan** [michaelbromley/angular-wordpress-seed#1]
I don't how to install angular-wordpress-seed.
clone  angular-wordpress-seed to wordpress folder or another folder?

**Comment by michaelbromley** [comment]
Did you see the instructions in the [readme](https://github.com/michaelbromley/angular-wordpress-seed#setting-up-wordpress)?

To answer your question, this repo just contains the code for the front-end client app, so you should not clone it to an existing Wordpress install. It can go anywhere you like, it just needs to be reachable via a web server.

If you already have a Wordpress install you want to use it with, you'll just need the JSON REST API plugin (basically follow steps 2 - 4 of the "Setting Up Wordpress" section)

**Comment by BruceYangMan** [comment]
Thank you reply i will try it again  :)

**Comment by violacase** [comment]
Hi Michael. It's not clear what exact wp-api plugin one should install. Better put a link to the right wp-repo file in your readme.

**Comment by michaelbromley** [comment]
@violacase good point - I added a link.

**Comment by jakecolour** [comment]
Hi Michael, I've installed the app + Wordpress JSON API. Have used same paths as repo. The posts from Wordpress aren't displaying though (on homepage and blog page). No javascript errors either. Everything else working fine and can view http://localhost/wordpress/wp-json. Any ideas?

**Comment by MurhafSousli** [comment]
Hi Michael, after running `gulp watch`, I got the folders (dist, build) but I don't know what to do next, I copied the contents of  'build` folder into the theme directory but nothing changed.

**Comment by michaelbromley** [comment]
@markor91 You don't need to copy the "build" folder anywhere, you need to serve it via HTTP and open it in a web browser. In this setup, you never directly view your Wordpress installation - it is just used behind-the-scenes by the Angular app to provide JSON content.

**Comment by MurhafSousli** [comment]
I'm sorry for being a newbie but it's not working with me. Can you explain more on how to get it work with WordPress!

**Comment by michaelbromley** [comment]
@markor91 No problem. Did you follow the instructions in the readme exactly? Can you tell me exactly what you tried and what happened?

**Comment by MurhafSousli** [comment]
Thank you, First maybe I didn't guess how to configure config.json, my current wordpress url is `http://localhost/wordpress` so I changed the urls to this.

```
"siteUrl": "http://localhost/wordpress/",
"basePath": "/angular-wordpress-seed/build/",
"apiUrl": "http://localhost/wordpress/wp-json/"
```

Second, When I run `gulp watch`, I first got 

```
Warnings: gulp version mismatch:
Global gulp is 3.9.0
Local gulp is 3.8.11
```

but then it completed the commands and built everything like it suppose to.
Now after I followed the instruction and I have the _build_ and _dist_ folders.
What should I do? copy the contents of build folder and paste it in the theme folder?
How should I test it on my wordpress website? http://localhost/wordpress

**Comment by michaelbromley** [comment]
@markor91 There is a concept that perhaps you didn't grasp yet: this project is _not_ a Wordpress theme. The intention is that you don't need to use Wordpress directly, so you don't need to "test" wordpress by going to `localhost/wordpress`. Rather, you need to test the Angular app by going to `localhost/angular-wordpress-seed/build/` in your browser. At this location, the Angular app will run and it will pull in the data from Wordpress via the REST API.

With that in mind, your config.json is not set up correctly. The `siteUrl` refers to the Angular app, not Wordpress. Therefore, if you have installed Wordpress at `localhost/wordpress`, and you have this project at `localhost/angular-wordpress-seed`, then your config.json should look just like in the example, namely:

```
"siteUrl": "http://localhost/angular-wordpress-seed/build/",
"basePath": "/angular-wordpress-seed/build/",
"apiUrl": "http://localhost/wordpress/wp-json/"
```

So try this: change the config.json to look like the example above, run gulp again to rebuild the app, and then in your browser, go to `http://localhost/angular-wordpress-seed/build/`.
