### ISSUE TITLE
Angular 4/REST API v2

### ISSUE THREAD

**Issue by botoxparty** [michaelbromley/angular-wordpress-seed#12]
Hey,

Would you consider updating this code to be compatible with Angular 4 and REST API v2 that is now included with Wordpress?

**Comment by michaelbromley** [comment]
Hi,

Sorry, I have no plans to do this. I don't use the Wordpress REST API anymore in any of my projects, and have no time to maintain this.

**Comment by botoxparty** [comment]
I have started an Angular 4 project here for anyone interested:

https://github.com/botoxparty/spliff
