### ISSUE TITLE
builds fine, can't reach build/index.html

### ISSUE THREAD

**Issue by linkingarts** [michaelbromley/angular-wordpress-seed#4]
Michael-

Thanks for making this code available.

AFAIK everything is right in my setup.

I've got the app running in my `sites.local/angular-wordpress-seed`
I've got an instance of WP-API-enabled wordpress running at `sites.local/wordpress/wp-json/`

My config reflects that:

`"build": {
      "siteUrl": "http://sites.local/angular-wordpress-seed/build/",
      "basePath": "/angular-wordpress-seed/build/",
      "apiUrl": "http://sites.local/wordpress/wp-json/"
    },`

Apache is running, serves the wordpress json fine.

Every time I run gulp watch then go to 

`http://sites.local/angular-wordpress-seed/`

I see the directory files, no problem. Then I try 

`http://sites.local/angular-wordpress-seed/build`

It can't find it and then tries www.sites.local/angular... etc.

I tried against ports 8000 and 8080 in case that was it. No luck. Changed all permissions to 775, no luck.

Is that config correct? Should I hit a different port?

**Comment by michaelbromley** [comment]
Hi,

First of all, what do you mean by "can't find it" - 404 error? Any message in the console? 

Have you looked at the built index.html file? All look normal? 

Do you have mod_rewrite enabled on your apache install? It's required by the html5mode urls. 

The port should not matter, just whatever port you serve http over.

**Comment by linkingarts** [comment]
I can run other angular apps no problem. It's not a 404, it's one of those
"browser can't find apex so it tries the www" things. So I try
http://sites.local/.../build and it times out, then tries
http://www.sites.local/.../build which of course just times out.

I've tried editing the file already, re-installing a fresh copy of your
repo.

Seems like maybe there's a permissions thing somewhere, and that it's
probably my setup somehow, though what I don't understand is why I can
build other angular apps no problem.

Is gulp watch running on :80?

thanks for the (quick!) response

On Mon, Aug 24, 2015 at 2:19 AM, Michael Bromley notifications@github.com
wrote:

> Hi,
> 
> First of all, what do you mean by "can't find it" - 404 error? Any message
> in the console?
> 
> Have you looked at the built index.html file? All look normal?
> 
> Do you have mod_rewrite enabled on your apache install? It's required by
> the html5mode urls.
> 
> The port should not matter, just whatever port you serve http over.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/michaelbromley/angular-wordpress-seed/issues/4#issuecomment-134070562
> .

## 

Peter Jacobson
Linking Arts
www.linkingarts.com
www.wedocracy.com
www.petejacobson.com
twitter.com/petejacobson
twitter.com/linkingarts
+1 504 264 6006 / VoIP
+1 504 503 2491 / mobile
peterjacobson / Skype

people + technology + art

**Comment by michaelbromley** [comment]
I think by default livereload (part of the watch task) runs on port 35729. Sorry I can't help further. If you figure it out, please note the solution here in case anyone else runs into it.

**Comment by linkingarts** [comment]
Will do, thx

On Tue, Aug 25, 2015 at 1:12 AM, Michael Bromley notifications@github.com
wrote:

> I think by default livereload (part of the watch task) runs on port 35729.
> Sorry I can't help further. If you figure it out, please note the solution
> here in case anyone else runs into it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/michaelbromley/angular-wordpress-seed/issues/4#issuecomment-134491800
> .

## 

Peter Jacobson
Linking Arts
www.linkingarts.com
www.wedocracy.com
www.petejacobson.com
twitter.com/petejacobson
twitter.com/linkingarts
+1 504 264 6006 / VoIP
+1 504 503 2491 / mobile
peterjacobson / Skype

people + technology + art

**Comment by cristiam86** [comment]
@linkingarts I finally solved this problem. After commenting/deleting the .htaccess sections that does it, you have to clean your Google Chrome's cache. 
I figured it out when, without doing nothing, I opened the same link on another browser and it worked.

**Comment by linkingarts** [comment]
ok will test, thx u

On Thu, Oct 1, 2015 at 5:08 AM, cristiam86 notifications@github.com wrote:

> @linkingarts https://github.com/linkingarts I finally solved this
> problem. After commenting/deleting the .htaccess sections that does it, you
> have to clean your Google Chrome's cache.
> I figured it out when, without doing nothing, I opened the same link on
> another browser and it worked.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/michaelbromley/angular-wordpress-seed/issues/4#issuecomment-144685983
> .

## 

Peter Jacobson
Linking Arts
www.linkingarts.com
www.wedocracy.com
www.petejacobson.com
twitter.com/petejacobson
twitter.com/linkingarts
+1 504 264 6006 / VoIP
+1 504 503 2491 / mobile
peterjacobson / Skype

people + technology + art
