### ISSUE TITLE
working locally but not on server

### ISSUE THREAD

**Issue by vtechmonkey** [michaelbromley/angular-wordpress-seed#7]
The app is not getting posts when I put it on my hosted server, but works fine locally.
Any idea why this would be?

These are the errors I'm getting in the console..

```
TypeError: Cannot read property 'length' of null
TypeError: e.ga is not a function
TypeError: Cannot assign to read only property 'excerpt' of <!doctype html>
```

and Batarang shows an empty array for featuredPosts. 

```
Models for (4)
 { 
    vm:  { 
           featuredPosts: 
                     [  ]
     } 
 } 
```

Looking forward to getting this running... :)

**Comment by vtechmonkey** [comment]
update to this issue -
I added the wordpress rewrite rules to the top of the htaccess file and the posts now appear on the hosted server. 

```
<ifModule mod_rewrite.c>
RewriteEngine On

  RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]



# Force www (http://stackoverflow.com/a/4958847/772859)
RewriteCond %{HTTP_HOST} !^localhost$
RewriteCond %{HTTP_HOST} !^www\. [NC]
RewriteCond %{HTTPS}s ^on(s)|
RewriteRule ^ http%1://www.%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

# allow social media crawlers to work by redirecting them to a server-rendered static version on the page
RewriteCond %{HTTP_USER_AGENT} (facebookexternalhit/[0-9]|Twitterbot|Pinterest|Google.*snippet|Googlebot|redditbot|bingbot)
RewriteRule blog/(\d*)/.*$ http://www.slicedbread.ie/static-page.php?id=$1 [P]

# Required to allow direct-linking of pages so they can be processed by Angular
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} !index
RewriteRule (.*) index.html [L]
```

</ifModule>

It doesn't work if I add them to the end of the file! 
The reason I was editing the htaccess file was because I couldn't login to the admin panel unless I restored the default wordpress htaccess file. 
I still can't login in either with the angular-wordpress-seed htaccess or my edited version, only with the original wordpress htaccess file.

**Comment by vtechmonkey** [comment]
another update..

login is working now, and posts. Everything is working!

I did also change the config.json line 11
to leave out api and just have
"http://www.example.com/wp-json"

Thank you for the app! :+1:

**Comment by michaelbromley** [comment]
Well done for sorting it out - didn't have a chance to really read the thread yet so I'm glad it didn't block you for too long.
