### ISSUE TITLE
Incorporating ACF support

### ISSUE THREAD

**Issue by dblodorn** [michaelbromley/angular-wordpress-seed#8]
Hello Michael - First off - this is an amazing project!
I'm enjoying digging into it - lot's to learn for sure!

Using Advanced Custom Fields with this project would be amazing, but I have run into issues getting it to fully work. I have used acf in a wordpress theme built with angular - but it was not using ui-router (and it was a theme).

also other things such as featured image seem to not work as one would think. Very curious.

{{ vm.post.featured_image.attachment_meta.sizes.thumbnail.url }} comes up blank.
as does {{ vm.post.acf.title }} (for example)

here's an example of what {{ vm.post.acf }} returns:
http://test.flatfiles.info/blog/23/bcn-bw

the source data source:
http://data.flatfiles.info/data-test/wp-json/posts/23/

Any thoughts would be extremely appreciated!

**Comment by dblodorn** [comment]
Sorry - cried wolf - seems to be more of an issue with serving the build site via localhost.
But I do love the project!

**Comment by michaelbromley** [comment]
Hi, no problem. Glad you got it fixed because I know nothing about ACF anyway...

**Comment by dblodorn** [comment]
Thanks Michael,
Its a great plugin for Wordpress development - The repeater filed is essential.
http://www.advancedcustomfields.com
